# Generated by Django 4.2.18 on 2025-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome1',
            new_name='nome',
        ),
    ]
